// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ifgzsebnBMAwLk9af6ar9kuiZkCTpeM',
    appId: '1:544864422423:web:596a164a0e54aa32652a52',
    messagingSenderId: '544864422423',
    projectId: 'ai-exam-c2f34',
    authDomain: 'ai-exam-c2f34.firebaseapp.com',
    storageBucket: 'ai-exam-c2f34.firebasestorage.app',
    measurementId: 'G-RXT7WL8SW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmoQQSne8I5nLjD3egcVg17Qht4h3nhAU',
    appId: '1:544864422423:android:446c12d330b5b21e652a52',
    messagingSenderId: '544864422423',
    projectId: 'ai-exam-c2f34',
    storageBucket: 'ai-exam-c2f34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgMaSPpA1xk5dM7TD0snm1ZTSFQRMb6xA',
    appId: '1:544864422423:ios:482e98668ac9863c652a52',
    messagingSenderId: '544864422423',
    projectId: 'ai-exam-c2f34',
    storageBucket: 'ai-exam-c2f34.firebasestorage.app',
    iosBundleId: 'com.Hyperlink.Development',
  );
}
